name: Build Kivy/Buildozer APK

on:
  # **SOLUCIÓN AL ERROR DE TIEMPO:** # Solo se ejecutará cuando hagas clic en el botón "Run workflow".
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Buildozer and Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libtool autoconf automake
          pip install buildozer
          
      - name: Build Android APK
        run: |
          buildozer android debug
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gestor-tasas-apk
          path: bin/gestor_tasas_app_json-*-debug.apk
