name: Build Kivy/Buildozer APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        # CRÍTICO: Usa la configuración más simple de checkout
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0 # Asegura que toda la rama sea descargada.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Buildozer and Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libtool autoconf automake
          pip install buildozer
          
      - name: Build Android APK
        run: |
          # Ahora el buildozer.spec debe estar presente.
          buildozer android debug
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gestor-tasas-apk
          path: bin/gestor_tasas_app_json-*-debug.apk
