name: Build Kivy/Buildozer APK

on:
  workflow_dispatch: 

jobs:
  build:
    # --- CRÍTICO: USAR UN CONTENEDOR DOCKER PRE-CONFIGURADO ---
    runs-on: ubuntu-latest
    container:
      # Esta imagen Docker contiene Buildozer, Kivy, Android SDK/NDK preinstalados y configurados.
      image: 'ghcr.io/x-c/buildozer-android:stable'
      
    steps:
      - name: Checkout Code
        # Descarga el código del repositorio
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0 
          
      # Eliminamos todos los pasos de instalación y licencia fallidos (pip install, apt install, mkdir...)
      
      - name: Create buildozer.spec
        # Recreamos el buildozer.spec con todas las correcciones de formato y dependencias (JSON)
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = Gestor Tasa JSON FINAL
          package.name = gestor_tasas_app_json
          package.domain = com.pcsoffice
          app.version = 1.1.24
          app.build = 86
          
          version.regex = (\d+)\.(\d+)\.(\d+)
          version.filename = buildozer.spec
          
          source.dir = .
          
          requirements = python3,kivy
          
          source.include_exts = py,png,jpg,kv,atlas,json
          source.include_dirs = tasa_data.json
          
          icon.filename = icon_app.png
          
          android.api = 27
          android.minapi = 21
          android.ndk = 21e
          android.build_tools = 28.0.3 
          
          android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
          
          log_level = 2
          
          [buildozer]
          
          log_level = 2
          warn_on_metaroot = 0
          EOF
        
      - name: Build Android APK
        # El comando 'buildozer' se ejecuta directamente dentro del contenedor funcional
        run: |
          buildozer android debug
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gestor-tasas-apk
          path: bin/gestor_tasas_app_json-*-debug.apk
