name: Build Kivy/Buildozer APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code (Forzado)
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0 

      - name: Install Buildozer and Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libtool autoconf automake
          
          pip install buildozer cython
          
      # --- PASO CRÍTICO 1: FORZAR ACEPTACIÓN DE LICENCIAS DEL SDK ---
      - name: Force Android SDK License Acceptance
        run: |
          mkdir -p ~/.android/
          touch ~/.android/repositories.cfg
          mkdir -p $ANDROIDSDK/licenses/
          # Crea el archivo de licencia necesario para desbloquear la descarga de Build-Tools
          echo 8933cc4444d37256d151a1460ec2770335ee9ed6 > $ANDROIDSDK/licenses/android-sdk-license
          
      # --- PASO CRÍTICO 2: CREAR EL buildozer.spec CON LA SOLUCIÓN REGEX Y APIs ESTABLES ---
      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = Gestor Tasa JSON FINAL
          package.name = gestor_tasas_app_json
          package.domain = com.pcsoffice
          app.version = 1.1.15
          app.build = 77
          
          # CRÍTICO: Forzamos la lectura de versión
          version.regex = (\d+)\.(\d+)\.(\d+)
          version.filename = buildozer.spec
          
          source.dir = .
          
          requirements = python3,kivy
          
          source.include_exts = py,png,jpg,kv,atlas,json
          source.include_dirs = tasa_data.json
          
          icon.filename = icon_app.png
          
          # --- CONFIGURACIÓN MÁS ESTABLE Y COMPATIBLE CON LICENCIAS ---
          android.api = 27
          android.minapi = 21
          android.ndk = 25b
          
          android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
          
          log_level = 2
          
          [buildozer]
          
          log_level = 2
          warn_on_metaroot = 0
          EOF
        
      - name: Build Android APK
        run: |
          buildozer android debug
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gestor-tasas-apk
          path: bin/gestor_tasas_app_json-*-debug.apk
